/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OcrRouteImport } from './routes/ocr'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ExtensionRouteImport } from './routes/extension'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CapturesRouteImport } from './routes/captures'
import { Route as BaseRouteImport } from './routes/base'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSisCaptureRouteImport } from './routes/api/sis-capture'
import { Route as ApiSavePartRouteImport } from './routes/api/save-part'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicSisCaptureRouteImport } from './routes/api/public/sis-capture'

const OcrRoute = OcrRouteImport.update({
  id: '/ocr',
  path: '/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionRoute = ExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CapturesRoute = CapturesRouteImport.update({
  id: '/captures',
  path: '/captures',
  getParentRoute: () => rootRouteImport,
} as any)
const BaseRoute = BaseRouteImport.update({
  id: '/base',
  path: '/base',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSisCaptureRoute = ApiSisCaptureRouteImport.update({
  id: '/api/sis-capture',
  path: '/api/sis-capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavePartRoute = ApiSavePartRouteImport.update({
  id: '/api/save-part',
  path: '/api/save-part',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSisCaptureRoute = ApiPublicSisCaptureRouteImport.update({
  id: '/api/public/sis-capture',
  path: '/api/public/sis-capture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/captures': typeof CapturesRoute
  '/chat': typeof ChatRoute
  '/extension': typeof ExtensionRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/ocr': typeof OcrRoute
  '/api/chat': typeof ApiChatRoute
  '/api/save-part': typeof ApiSavePartRoute
  '/api/sis-capture': typeof ApiSisCaptureRoute
  '/api/public/sis-capture': typeof ApiPublicSisCaptureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/captures': typeof CapturesRoute
  '/chat': typeof ChatRoute
  '/extension': typeof ExtensionRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/ocr': typeof OcrRoute
  '/api/chat': typeof ApiChatRoute
  '/api/save-part': typeof ApiSavePartRoute
  '/api/sis-capture': typeof ApiSisCaptureRoute
  '/api/public/sis-capture': typeof ApiPublicSisCaptureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/base': typeof BaseRoute
  '/captures': typeof CapturesRoute
  '/chat': typeof ChatRoute
  '/extension': typeof ExtensionRoute
  '/favorites': typeof FavoritesRoute
  '/history': typeof HistoryRoute
  '/import': typeof ImportRoute
  '/ocr': typeof OcrRoute
  '/api/chat': typeof ApiChatRoute
  '/api/save-part': typeof ApiSavePartRoute
  '/api/sis-capture': typeof ApiSisCaptureRoute
  '/api/public/sis-capture': typeof ApiPublicSisCaptureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/base'
    | '/captures'
    | '/chat'
    | '/extension'
    | '/favorites'
    | '/history'
    | '/import'
    | '/ocr'
    | '/api/chat'
    | '/api/save-part'
    | '/api/sis-capture'
    | '/api/public/sis-capture'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/base'
    | '/captures'
    | '/chat'
    | '/extension'
    | '/favorites'
    | '/history'
    | '/import'
    | '/ocr'
    | '/api/chat'
    | '/api/save-part'
    | '/api/sis-capture'
    | '/api/public/sis-capture'
  id:
    | '__root__'
    | '/'
    | '/base'
    | '/captures'
    | '/chat'
    | '/extension'
    | '/favorites'
    | '/history'
    | '/import'
    | '/ocr'
    | '/api/chat'
    | '/api/save-part'
    | '/api/sis-capture'
    | '/api/public/sis-capture'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaseRoute: typeof BaseRoute
  CapturesRoute: typeof CapturesRoute
  ChatRoute: typeof ChatRoute
  ExtensionRoute: typeof ExtensionRoute
  FavoritesRoute: typeof FavoritesRoute
  HistoryRoute: typeof HistoryRoute
  ImportRoute: typeof ImportRoute
  OcrRoute: typeof OcrRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSavePartRoute: typeof ApiSavePartRoute
  ApiSisCaptureRoute: typeof ApiSisCaptureRoute
  ApiPublicSisCaptureRoute: typeof ApiPublicSisCaptureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ocr': {
      id: '/ocr'
      path: '/ocr'
      fullPath: '/ocr'
      preLoaderRoute: typeof OcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extension': {
      id: '/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof ExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captures': {
      id: '/captures'
      path: '/captures'
      fullPath: '/captures'
      preLoaderRoute: typeof CapturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/base': {
      id: '/base'
      path: '/base'
      fullPath: '/base'
      preLoaderRoute: typeof BaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sis-capture': {
      id: '/api/sis-capture'
      path: '/api/sis-capture'
      fullPath: '/api/sis-capture'
      preLoaderRoute: typeof ApiSisCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/save-part': {
      id: '/api/save-part'
      path: '/api/save-part'
      fullPath: '/api/save-part'
      preLoaderRoute: typeof ApiSavePartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sis-capture': {
      id: '/api/public/sis-capture'
      path: '/api/public/sis-capture'
      fullPath: '/api/public/sis-capture'
      preLoaderRoute: typeof ApiPublicSisCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaseRoute: BaseRoute,
  CapturesRoute: CapturesRoute,
  ChatRoute: ChatRoute,
  ExtensionRoute: ExtensionRoute,
  FavoritesRoute: FavoritesRoute,
  HistoryRoute: HistoryRoute,
  ImportRoute: ImportRoute,
  OcrRoute: OcrRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSavePartRoute: ApiSavePartRoute,
  ApiSisCaptureRoute: ApiSisCaptureRoute,
  ApiPublicSisCaptureRoute: ApiPublicSisCaptureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
